global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: durably-server
    metrics_path: /metrics
    static_configs:
      - targets: ['server:3000']
        labels:
          component: server

  - job_name: durably-worker
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:9090']
        labels:
          component: worker
